### ISSUE TITLE
"nanomod-overlay --update" fails on devices with adopted storage.

### ISSUE THREAD

**Issue by ShapeShifter499** [Nanolx/NanoMod#10]
I like to use Adopted storage on my device and I just noticed that causes 'nanomod-overlay' to fail if your updating the configuration since the location for the configuration is hard coded. The location '/data/media/0' isn't really used anymore and files residing there usually get moved to the newly formatted and adopted SD card.

**Comment by Nanolx** [comment]
what's the path for adopted storage?

**Comment by ShapeShifter499** [comment]
The location as seen when mount the phone on a PC is at 
/storage/emulated/0/

**Comment by Nanolx** [comment]
I changed the paths to:

`/data/.nanomod-overlay`

and

`/data/.nanomod-setup`

if old files are found in

'/data/media/0/`

are found, they will be moved to the new location. This is the easiest setup, as I don't have to care about different setups when the files are in `/data`.

**Comment by ShapeShifter499** [comment]
In the root of /data totally works, thanks for the fix.
