### ISSUE TITLE
Framework Patcher Request: Support for Ground Zero ROM Tesla build

### ISSUE THREAD

**Issue by JERW86** [Nanolx/NanoMod#12]
Hi @Nanolx 

I tried to patch GZR Tesla XDA Link: https://forum.xda-developers.com/moto-g4-plus/development/7-1-1-ground-zero-roms-validus-tesla-t3553036 but it didn't work. I tried to apply the patch using the on- board pacher using Nanomod microG, then again directly to system. Each time, before flashing the patcher, I booted into system, and both times, TWRP mentioned 'error 1'.

To make sure the problem was not my phone or TWRP, I flashed Nanomod microG and the patcher on Reserection Remix. It worked perfectly!

Here is the services.jar from the Tesla build: 
[TWRP Logs and services.jar.zip](https://github.com/Nanolx/NanoMod/files/949384/TWRP.Logs.and.services.jar.zip)

  Please let me know if you need more files from /system/framework.

Info: 
Phone: XT1625 (Moto G 2016 Non-Amazon)
Latest Official TWRP athene 3.1.0-0

Thank you for your work and support.

**Comment by Nanolx** [comment]
It fails on `zip`. Does Tesla ship a `zip` binary? Either way, create a new patcher zip for from github repository using `mod.sh patcher`. The latest in-development version does ship it's own `zip` binary, as several ROMs don't have one.

**Comment by JERW86** [comment]
I don't know if Tesla ships with a zip binary. I'll ask the maintainer for my device. I flashed the latest patcher from this repo, but it didn't work.
Steps
1. Full wipe
2. Flash Tesla (ships with Magisk v12 built in)
3. Flash ElementalX 1.05 LOS Kernel
4. Flash Nanomod microG build 04-21-17
5.Wipe delvick/cashe
6.Reboot System
7. Boot and wait a few minutes
8. Reboot Recovery and flash patcher test zip from github
Result: error 1 at zip 
Log: 
[Test Patcher Github 4-23-17 recovery.txt](https://github.com/Nanolx/NanoMod/files/950507/Test.Patcher.Github.4-23-17.recovery.txt)

**Comment by Nanolx** [comment]
OK. I think I've found the issue

a) the ROM does not have it's own `zip`
b) the `framework-patcher`'s own `zip` is not properly setup

I've created two test flashable zips, please test **both** (even if the first one works for you)
* [test1](https://www.androidfilehost.com/?fid=529152257862721723)
* [test2](https://www.androidfilehost.com/?fid=529152257862721724)

actually both should work.

**Comment by JERW86** [comment]
Test zips 1 and 2 were both successful!
Steps: 
Full wipe
Flash Tesla (ships with Magisk v12 built in)
Flash ElementalX 1.05 LOS Kernel (optional)
Flash Nanomod microG build 04-21-17
Wipe delvick/cashe
Reboot System
Boot and wait a few minutes
Reboot Recovery and flash patcher test 1
Result: successful!

Repeat exact same steps only flash patcher test 2 zip
Result: successful!
Thank you!

**Comment by Nanolx** [comment]
Closing this issue as [fixed], latest git HEAD already contains the fix.
