### ISSUE TITLE
nanomod config files on multiple locations

### ISSUE THREAD

**Issue by Generator** [Nanolx/NanoMod#13]
Placing nanomod-overlay and nanomod-setup on /data isn't very practical in case of fresh install, since on fresh install will (full) wipe /system, /data, dalvik-cache and cache.

However giving the user to have multiple choices to place config files like on /sdcard or nanomod zip directory users can pre-config nanomod before installation and install do a quicker install trough custom recoveries.

Something like opengapps does with gapps-config file:

```
# Locate gapps-config (if used)
for i in "$TMP/aroma/.gapps-config"\
 "$zip_folder/.gapps-config-$device_name"\
 "$zip_folder/gapps-config-$device_name.txt"\
 "/sdcard/Open-GApps/.gapps-config-$device_name"\
 "/sdcard/Open-GApps/gapps-config-$device_name.txt"\
 "$zip_folder/.gapps-config"\
 "$zip_folder/gapps-config.txt"\
 "/sdcard/Open-GApps/.gapps-config"\
 "/sdcard/Open-GApps/gapps-config.txt"\
 "$zip_folder/.gapps-config-$device_name.txt"\
 "/sdcard/Open-GApps/.gapps-config-$device_name.txt"\
 "$zip_folder/.gapps-config.txt"\
 "/sdcard/Open-GApps/.gapps-config.txt"\
 "/persist/.gapps-config-$device_name"\
 "/persist/gapps-config-$device_name.txt"\
 "/persist/.gapps-config"\
 "/persist/gapps-config.txt"\
 "/persist/.gapps-config-$device_name.txt"\
 "/persist/.gapps-config.txt"\
 "/tmp/install/gapps-config.txt"\
 "/tmp/install/.gapps-config-$device_name.txt"\
 "/tmp/install/.gapps-config.txt"; do
  if [ -r "$i" ]; then
    g_conf="$i";
    break;
  fi;
done;
```
some file locations like:

```
/data/.nanomod-setup
/sdcard/nanomod-setup
/sdcard/.nanomod-setup
/sdcard/NanoMod/nanomod-setup
/persist/nanomod-setup
$nanomod_folder/nanomod-setup
```

**Comment by thewisenerd** [comment]
yes; also, /data isn't /sdcard in most cases, the XDA thread OP needs to be reworded a bit ^_^

( i spent 3 wipe/re-installs because i didn't know why my ```nanomod.play=2``` in ```/sdcard/.nanomod-setup``` didn't work, then looked at source )

**Comment by thewisenerd** [comment]
here (https://github.com/thewisenerd/NanoMod/commit/c72dd2e0f10a8dd401fc9dff244d3ac615b0ea4a) I've written a small patch for microG (because I only use that :stuck_out_tongue: )

**Comment by Nanolx** [comment]
I pushed something similar to the git repository, but for both full and microG packages. Currently testing on my Tablet.

And yes, seems I forgot to replace one instance of `/sdcard` in README.xda (pre-6.1 files were stored /sdcard, but that collides with adoptable storage).

**Comment by Nanolx** [comment]
So the installers now check for `.nanomod-setup` , `.nanomod-apps` and `.nanomod-overlay` in

* `/data`
* `/sdcard`
* `/external_sd` (special path for `/storage/$UUID` in TWRP)
* `/persist`
* directory where the zip is stored

**Comment by Nanolx** [comment]
README updated
