### ISSUE TITLE
Provided MagiskManager lacking private library

### ISSUE THREAD

**Issue by xenithorb** [Nanolx/NanoMod#15]
Have you done any testing recently with being able to install modules _after_ NanoMod? 

OS: LineageOS 14.1 build 20170508 for bacon
Phone: OnePlus One 
Nanomod: 7.1-20170501

I'm seeing this recently and I think it was causing bootloops for me - basically I can't:

1. Install a module in TWRP after nanomod - causes bootloop - this includes the patcher and my own relatively simple custom module that only adds a single file to the overlay. 
2. If I only install Magisk and Nanomod, it boots, but we get this error in logcat if I try to install a module from the Magisk Manager:

```
05-08 17:13:29.892 14749 17114 W System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/MagiskManager/MagiskManager.apk"],nativeLibraryDirectories=[/system/app/MagiskManager/lib/arm, /system/app/MagiskManager/MagiskManager.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]] couldn't find "libzipadjust.so"
05-08 17:13:29.892 14749 17114 W System.err:    at java.lang.Runtime.loadLibrary0(Runtime.java:984)
05-08 17:13:29.892 14749 17114 W System.err:    at java.lang.System.loadLibrary(System.java:1562)
05-08 17:13:29.892 14749 17114 W System.err:    at com.topjohnwu.magisk.utils.ZipUtils.<clinit>(Unknown Source)
05-08 17:13:29.892 14749 17114 W System.err:    at com.topjohnwu.magisk.utils.ZipUtils.a(Unknown Source)
05-08 17:13:29.892 14749 17114 W System.err:    at com.topjohnwu.magisk.a.b.a(Unknown Source)
05-08 17:13:29.892 14749 17114 W System.err:    at com.topjohnwu.magisk.a.b.a(Unknown Source)
05-08 17:13:29.892 14749 17114 W System.err:    at com.topjohnwu.magisk.a.b.doInBackground(Unknown Source)
05-08 17:13:29.892 14749 17114 W System.err:    at android.os.AsyncTask$2.call(AsyncTask.java:305)
05-08 17:13:29.892 14749 17114 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-08 17:13:29.892 14749 17114 W System.err:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
05-08 17:13:29.892 14749 17114 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-08 17:13:29.892 14749 17114 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-08 17:13:29.892 14749 17114 W System.err:    at java.lang.Thread.run(Thread.java:761)
```

If this isn't related to you then please ignore, but I recall you doing something with zip. The reason I can't test Magisk w/out NanoMod at the moment is that I rely on it to not lose F-Droid and more importantly microG userdata (meaning when it appears missing, android deletes the userdata and therefore all of the push authorizations and that's very difficult to redo).

**Comment by xenithorb** [comment]
Yeah something is up here. I went ahead and uninstalled magisk and skipped nanomod....If I don't install nanomod (although now it's a pain to get MM, F-droid, Yalp, and GmsCore in /system/priv-app) nothing bootloops and I can install other modules fine - AND adding them through MM doesn't error out like it did above. Your module is doing something wonky

**Comment by Nanolx** [comment]
I've fixed the Magisk Manager issue with the latest commit.

Need to test more.

**Comment by xenithorb** [comment]
I'd like to report that the original issue on the ticket has been fixed quite some time ago. 

I would also like to report that 9.1 (current DEV, untested anything between 7.2 and 9.1) now works again and doesn't bootloop my device anymore. I wish I understood more deeply why, but I could never pinpoint why it was boot looping in the first place. (How do you troubleshoot that when adb doesn't even start yet?)

I haven't changed anything about my procedure, nor has the Magisk version changed, so it must be down to something with the ROM (lineage-14.1-20170605-nightly-bacon-signed.zip) or Nanomod itself, but I don't have the time to figure out what change, I'm just glad it works again for the time being.
