### ISSUE TITLE
external_sd script might cause issues with adopted storage.

### ISSUE THREAD

**Issue by ShapeShifter499** [Nanolx/NanoMod#18]
/overlay/system/etc/init.d/external_sd

The above script might cause issues with adopted storage, can you please include an option not to include it?  I do want the other init.d scripts.

**Comment by Nanolx** [comment]
It just creates a symlink, so I don't actually see any major issue here.

Either way, since you use adoptable storage, please post the full ouput of `mount`.

**Comment by ShapeShifter499** [comment]
When I tried the script anyways my system seemed to have gotten confused, half of my files appeared to be "missing" but were accessible again after removing the external_sd script.

Attached is the output of the mount command ran as root from my phone including adopted storage.
[mount.txt](https://github.com/Nanolx/NanoMod/files/1047534/mount.txt)

**Comment by Nanolx** [comment]
I doubt that's in any way related to that script: it's either related to logscleaner or sqlite, I had it once, too, but never again, it's a rare issue.

Again, external_sd just creates a symlink, it can't cause any side effect, especially not that drastic.

I'll have a look at mount.txt

**Comment by ShapeShifter499** [comment]
I left the other scripts in place, still working now afaik.  I only removed the external_sd script.

**Comment by Nanolx** [comment]
I've updated the `external_sd` script to be better, but as I expected it did nothing with adoptable storage in first place, because it explicitly checks for SD Cards.
