### ISSUE TITLE
GmsCore appears corrupted when installing it. 

### ISSUE THREAD

**Issue by ShapeShifter499** [Nanolx/NanoMod#23]
I get this message trying to install GmsCore as a user app from the latest git repository grab, version 9.4

**Comment by Nanolx** [comment]
While I don't know why you'd do that, it's fixed.

**Comment by ShapeShifter499** [comment]
This is for sure fixed?  I got a Play services crash right when I booted up after updating my device (LineageOS + NanoMod zip). So I figured I might still need to install it.

**Comment by Nanolx** [comment]
Fixed with yesterday's commit. If you refer to Magisk Issue 155, GmsCore was never effected.

If an(other) issue still occurs, I need a logcat in a new issue.

**Comment by ShapeShifter499** [comment]
I just updated to the latest LineageOS 14.1 nightly June 26. After only installing the DroidGuard apk I seem to have no further issues.
