### ISSUE TITLE
Include microG apps Map API v1

### ISSUE THREAD

**Issue by ShapeShifter499** [Nanolx/NanoMod#6]
I would like to see microG apps Map Framework API v1 to be included https://github.com/microg/android_frameworks_mapsv1/releases

As I understand it, some older apps require this because they still use the old v1 Maps API from Google.

**Comment by Nanolx** [comment]
I'll have a look at it.

**Comment by Nanolx** [comment]
Done. I added the new

`nanomod.mapsv1`

setup option for the `nanomod-setup` file. By default this is **not** installed, so make sure that you add

`nanomod.mapsv1=1`

to your `/sdcard/.nanomod-setup` file. For more infos on how this works, check **Alter Installation** in the README.

**Comment by ShapeShifter499** [comment]
Thank you
