### ISSUE TITLE
microG Services Core as user app?

### ISSUE THREAD

**Issue by ShapeShifter499** [Nanolx/NanoMod#7]
I thought all of microG could be installed as user apps but trying to install your signed version of "microG Services Core" GmsCore.apk results in the package manager telling me "The package appears to be corrupt."   I was doing this preemptively to avoid https://github.com/topjohnwu/Magisk/issues/155 However the app does work normally and runs fine as a system app in the overlay.

**Comment by Nanolx** [comment]
It complains about AndroidManifest.xml, indeed. But I haven't touch the Manifest. I'll debug this issue the next days.

**Comment by ShapeShifter499** [comment]
@Nanolx any updates on this?

**Comment by Nanolx** [comment]
Not yet.

**Comment by Nanolx** [comment]
fixed

**Comment by ShapeShifter499** [comment]
@Nanolx Seems like the issue has popped up again

**Comment by Nanolx** [comment]
Nope, I guess you mean Issue #3

**Comment by ShapeShifter499** [comment]
It's not letting me install the microG framework as a user app, it still complains it's corrupted.

**Comment by Nanolx** [comment]
Not on my devices... logcat?

Am 5. Mai 2017 04:14:26 MESZ schrieb Lance <notifications@github.com>:
>It's not letting me install the microG framework as a user app, it
>still complains it's corrupted.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nanolx/NanoMod/issues/7#issuecomment-299355428

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Nanolx** [comment]
Fixed again, seems it complained about the apk not being page aligned.

**Comment by ShapeShifter499** [comment]
I'm sorry I did not post a logcat sooner, I've been a bit busy. Thank you for the fix though I just tested it right now and it appears to install just fine.
